# Generated by Django 2.1.4 on 2020-07-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='pwd',
            new_name='password',
        ),
    ]
