# Generated by Django 2.1.4 on 2020-07-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200716_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
